name: bookly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  go_router: ^13.2.0
  cupertino_icons: ^1.0.2

  #api
  dartz: ^0.10.1
  dio: ^5.4.1
  #local_data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #get: ^4.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
